### ISSUE TITLE
The following specifications were found to be incompatible with your system

### ISSUE THREAD

**Issue by tkrwy** [samsledje/MLSB2021_PLM_DTI#3]
Thank you for your great work! When I created my environment using  "conda env create -f environment.yml ", I met with the following problem. Is there other ways to create the environment? 
The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - feature:/linux-64::__linux==4.18.0=0
  - feature:/linux-64::__unix==0=0
  - feature:|@/linux-64::__glibc==2.28=0
  - feature:|@/linux-64::__linux==4.18.0=0
  - feature:|@/linux-64::__unix==0=0
  - alsa-lib==1.2.6.1=h7f98852_0 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - argon2-cffi-bindings==21.2.0=py37h7f8727e_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - blas==2.114=mkl -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - boost-cpp==1.74.0=h6cacc03_7 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - brotli-bin==1.0.9=h166bdaf_7 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - brotli==1.0.9=h166bdaf_7 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
...
  - yaml==0.2.5=h7b6447c_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - zeromq==4.3.4=h2531618_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - zlib==1.2.11=h166bdaf_1014 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - zstd==1.5.2=h8a70e8d_1 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.28

**Comment by samsledje** [comment]
Hi tkrwy -- please try downloading ConPLex from pip using `pip install conplex-dti`, you can see further information on the primary repository https://github.com/samsledje/ConPLex. Please let me know if you continue to have issues.

**Comment by tkrwy** [comment]
Hi samsledje--It works! Thank you very much!
