### ISSUE TITLE
AttributeError: module 'src.architectures' has no attribute 'SimpleCoembeddingNoSigmoid

### ISSUE THREAD

**Issue by theslugger** [samsledje/MLSB2021_PLM_DTI#5]
`AttributeError: module 'src.architectures' has no attribute 'SimpleCoembeddingNoSigmoid'`

In `default_config.yaml`, model_architecture is set to `SimpleCoembeddingNoSigmoid`, but in `src.architectures`, there is actually no such class, so getting it should change it to `SimpleCoembedding`. Is this correct?

**Comment by samsledje** [comment]
Hi @theslugger ,

Yes, changing to SimpleCoembedding should work. In general, I'd recommend you use the regularly updated package version of ConPLex (https://github.com/samsledje/ConPLex), rather than this development repository. Let me know if you have any more questions!
